### ISSUE TITLE
A few questions about how the project is managed

### ISSUE THREAD

**Issue by harfangk** [elm-jp/guide#115]
Greetings!

I'm trying to set up a Korean translation of the Elm guide, and your guide is so well maintained that I'd like to learn about your translation process to benchmark it. I have a few questions though!

1. Custom workflow
Many projects use tools like https://www.crowdin.com or https://www.transifex.com, but you are using a custom workflow with `npx pretranslate` for commented out paragraphs. What considerations led you to this decision?

2. Tracking changes to original text
The original guide is in a different repository. How do you track changes to the original text and check if there are newer texts, and mark the new text as needing translation? For example, in https://github.com/elm-jp/guide/commit/1a0b117dc01f207c71e3c8008f04a62f752d842a you have updated the original text and removed old translation. Is that process done manually or automatically?

Those two are the biggest questions I have, and would help me a lot when deciding the process. Thank you very much!

**Comment by arowM** [comment]
Hi!
도움이 되어, 영광입니다.

## Custom workflow

In fact, we have discussed about such tools in #70.
The reason why we have decided not to use them is because they are for **translation of applications** rather than **translation of documents**.
So, we have felt that they are too complex for our use case and even does not have enough feature to meet our needs.

The `npx pretranslate` also tells us when there are important terms we have translated before by checking translation table in `about_translation.md`.

## Tracking changes to original text

I do update translations by my hand with the aid of `git`.

Here is my way to do that with git.

1. Beforehand, register Evan's original repository as another remote.

```
$ git remote add evan github:evancz/guide.elm-lang.org.git
$ git remote -v
evan	github:evancz/guide.elm-lang.org.git (fetch)
evan	github:evancz/guide.elm-lang.org.git (push)
origin	github:elm-jp/guide.git (fetch)
origin	github:elm-jp/guide.git (push)
```

2. Update `evan/origin` and merge.

```
$ git checkout master
$ git fetch evan
$ git checkout -b merge-evan
$ git merge evan/master
```

By this way, I can know which parts were actually updated.

**Comment by arowM** [comment]
Here are other notable things we are doing.

* We believe that our translations should be more natural Japanese and easy to understand rather than be strict to original sentences

    It is because the purpose of the Elm guide is to introduce Elm.
    If someone requires strictness, they should read English version ;)
    The fact is explained in [about_translation.html](https://guide.elm-lang.jp/about_translation.html).

* We shows our translations are up to date by providing diff.

    It is the link named "翻訳がベースとしているバージョンと英語版の最新バージョンとの差分" in [about_translation.html](https://guide.elm-lang.jp/about_translation.html).
